version: '3'

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn Emarket.wsgi:application -b 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/back/web/staticfiles
      - media_volume:/home/back/web/media  
    env_file:
      - ./.env.prod
    
  nginx:
    build: ./nginx
    ports:
     - 1337:80 
    volumes:
      - static_volume:/home/back/web/staticfiles
      - media_volume:/home/back/web/media
    depends_on:
     - web

volumes:
  static_volume:
  media_volume:
     
